In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])

In [4]:
x

array([1, 2, 3])

In [5]:
y = np.array([2, 3.9, 6.1])

In [6]:
y

array([2. , 3.9, 6.1])

In [7]:
# 平均の算出
x.mean()

2.0

In [8]:
y.mean()

4.0

In [9]:
# 中心化
xc = x - x.mean()

In [10]:
xc

array([-1.,  0.,  1.])

In [11]:
yc = y - y.mean()

In [12]:
yc

array([-2. , -0.1,  2.1])

In [13]:
# 要素ごとの掛け算（要素積）
xx = xc * xc

In [14]:
xx

array([1., 0., 1.])

In [15]:
xy = xc * yc

In [16]:
xy

array([ 2. , -0. ,  2.1])

In [17]:
xx.sum()

2.0

In [18]:
xy.sum()

4.1

In [19]:
a = xy.sum() / xx.sum()

In [20]:
a

2.05

In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('sample.csv')

In [26]:
df.head(3)

x         y
0  40.362  137500.0
1  40.686  132500.0
2  38.430   93000.0

In [28]:
x = df['x']
y = df['y']