In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [3]:
x

array([1, 2, 3])

In [4]:
y = np.array([2, 3.9, 6.1])

In [5]:
y

array([2. , 3.9, 6.1])

In [6]:
# 平均の算出
x.mean()

2.0

In [7]:
y.mean()

4.0

In [9]:
# 中心化
xc = x - x.mean()

In [10]:
xc

array([-1.,  0.,  1.])

In [11]:
yc = y - y.mean()

In [12]:
yc

array([-2. , -0.1,  2.1])

In [13]:
# 要素ごとの掛け算（要素積）
xx = xc * xc

In [14]:
xx

array([1., 0., 1.])

In [17]:
xy = xc * yc

In [18]:
xy

array([ 2. , -0. ,  2.1])